apiVersion: v1
kind: Service
metadata:
  name: eval-node-http-min
  labels:
    app.kubernetes.io/name: eval-node-http-min
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: eval-node-http-min
    app.kubernetes.io/managed-by: kubectl
spec:
  type: NodePort
  selector:
    app: eval-node-http-min
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
